baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Oxford English Hub Support'
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn-main"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableLandingPageButton = false
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = true


# For creating the 'More' menu at the bottom of the sidebar
[[menu.shortcuts]]
name = "<i class='fas fa-headset'></i> Contact us"
identifier = "ds"
url = "https://github.com/McShelby/hugo-theme-relearn"
weight = 10

# [[menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Showcases"
# url = "/showcase/"
# weight = 11